use_frameworks!

platform :ios, '9.0'

target 'NTBiometrictValidator_Example' do
  pod 'NTBiometrictValidator', :path => '../'

  target 'NTBiometrictValidator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
